version: '3.5'

services:
  mordor-caldera:
    image: cyb3rward0g/caldera:0.0.1
    container_name: mordor-caldera
    volumes:
      - ./config/a93f6915-a9b8-4a6b-ad46-c072963b32c1.yml:/opt/Caldera/data/facts/a93f6915-a9b8-4a6b-ad46-c072963b32c1.yml
      - ./config/03afada1-1714-408f-bde5-f528b91dc89d.yml:/opt/Caldera/data/abilities/defensive-evasion/03afada1-1714-408f-bde5-f528b91dc89d.yml
    restart: always
    environment:
      CALDERA_IP: ${CALDERA_IP}
      CALDERA_ADMIN_NAME: ${CALDERA_ADMIN_NAME}
      CALDERA_ADMIN_PASSWORD: ${CALDERA_ADMIN_PASSWORD}
    ports:
      - "80:80"
      - "443:443"
      - "8888:8888"
    networks:
      caldera:

networks:
  caldera:
    driver: bridge